### ISSUE TITLE
Fatal error with Laravel >=5.2 and PHP >=7.2

### ISSUE THREAD

**Issue by s3huber** [Propaganistas/Laravel-Cache-Keywords#6]
> Declaration of Propaganistas\LaravelCacheKeywords\KeywordsRepository::put($key, $value, $minutes) must be compatible with Illuminate\Cache\Repository::put($key, $value  
  , $minutes = NULL)

This is due the signature of the `\Illuminate\Cache\Repository::put` method was changed to `public function put($key, $value, $minutes = null)` with Laravel 5.2. The third parameter `$minutes` was changed to be optional. The implementation `\Propaganistas\LaravelCacheKeywords\KeywordsRepository::put` currently does not declare this parameter as optional.

Since PHP 7.2 this yields in a fatal error.

**Comment by Propaganistas** [comment]
Thanks for reporting. A new release is on its way.
